# Generated by Django 3.2.4 on 2021-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
