# Generated by Django 3.2.4 on 2021-07-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_products_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.productslottery')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
