# Generated by Django 3.2.4 on 2021-07-06 05:05

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lotteryparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryparticipants',
            name='screenshot',
            field=models.ImageField(default=True, upload_to=apps.users.models.user_directory_path),
            preserve_default=False,
        ),
    ]
