# Generated by Django 3.2.4 on 2021-07-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210706_0512'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lotteryparticipants',
            unique_together={('lottery', 'number')},
        ),
    ]
