# Generated by Django 3.2.4 on 2021-07-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lotteryparticipants')),
            ],
        ),
    ]
