# Generated by Django 3.2.4 on 2021-07-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_productfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_type',
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Торт', 'Торт'), ('Пицца', 'Пицца'), ('Суши', 'Суши')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.products')),
            ],
        ),
    ]
