# Generated by Django 3.2.4 on 2021-07-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210707_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_product', to='users.products'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_product', to='users.products'),
        ),
    ]
