# Generated by Django 3.2.4 on 2021-07-08 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_auto_20210708_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorite', to='users.products'),
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
