# Generated by Django 3.2.4 on 2021-07-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_products_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Category',
        ),
    ]
