# Generated by Django 3.2.4 on 2021-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_lotteryparticipants_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotteryparticipants',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
