# Generated by Django 3.2.4 on 2021-07-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default="Ust-aldan", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='village',
            field=models.CharField(default="Kepteni", max_length=50),
            preserve_default=False,
        ),
    ]
